packages:
  - packages/*
  - subgraphs/*

catalog:
  "@emotion/is-prop-valid": ^1.4.0
  "@eslint/js": ^10.0.1
  "@graphprotocol/graph-cli": ^0.98.1
  "@graphprotocol/graph-ts": 0.38.1
  "@tanstack/eslint-plugin-query": ^5.101.4
  "@tanstack/react-query": ^5.101.4
  "@types/mustache": ^4.2.6
  "@types/node": ^26.2.0
  "@types/react": ^19.2.18
  "@types/react-dom": ^19.2.4
  classnames: ^2.5.1
  dayjs: ^1.11.23
  eslint: ^10.9.0
  eslint-config-next: 16.3.2
  eslint-config-prettier: ^10.1.8
  eslint-config-turbo: ^2.10.11
  eslint-plugin-prettier: ^5.5.6
  eslint-plugin-react-hooks: ^7.1.1
  globals: ^17.11.0
  motion: ^13.1.1
  mustache: ^4.2.0
  prettier: ^3.9.6
  react: ^19.2.8
  react-dom: ^19.2.8
  react-remove-scroll: ^2.7.2
  react-use: ^17.6.1
  sonner: ^2.0.8
  tailwindcss: ^4.3.3
  tsx: ^4.23.12
  typescript: ^6.0.3
  typescript-eslint: ^8.67.0
  viem: ^2.55.19
  vite: ^8.2.2
  wagmi: ^3.7.6

allowBuilds:
  "@parcel/watcher": false
  "@reown/appkit": false
  "@swc/core": false
  bufferutil: false
  esbuild: false
  keccak: false
  protobufjs: false
  secp256k1: false
  sharp: false
  unrs-resolver: false
  utf-8-validate: false
  workerd: false

minimumReleaseAge: 5760 # 4 days in minutes
minimumReleaseAgeExclude:
  - "@metrom-xyz/sdk"
  - "@metrom-xyz/contracts"
  - "@metrom-xyz/aptos-contracts"
  - "@metrom-xyz/programs-solana"
  - "@metrom-xyz/sui-contracts"
blockExoticSubdeps: true
