// this file is automatically generated by the /scripts/generate-addresses-files.ts
// script, do not edit this manually

import { Address } from "@graphprotocol/graph-ts";

export const FACTORY_ADDRESS = Address.fromString("0x0000000000000000000000000000000000000000");
export const NON_FUNGIBLE_POSITION_MANAGER_ADDRESS = Address.fromString("0x0000000000000000000000000000000000000000");
