// this file is automatically generated by the /scripts/generate-addresses-file.ts
// script, do not edit this manually

import { Address } from "@graphprotocol/graph-ts";

export const FACTORY_ADDRESS = Address.fromString("0xAfE208a311B21f13EF87E33A90049fC17A7acDEc");
export const NON_FUNGIBLE_POSITION_MANAGER_ADDRESS = Address.fromString("0x3d79EdAaBC0EaB6F08ED885C05Fc0B014290D95A");
