export const metromAptosAbi = {
    address:
        "0xe1c55a37640ff4582a47bacd396e3409056f2e931b5dd8dc6ef6ef131cf5cc9e",
    name: "metrom",
    friends: [],
    exposed_functions: [
        {
            name: "owner",
            visibility: "public",
            is_entry: false,
            is_view: true,
            generic_type_params: [],
            params: [],
            return: ["address"],
        },
        {
            name: "distribute_rewards",
            visibility: "public",
            is_entry: true,
            is_view: false,
            generic_type_params: [],
            params: ["&signer", "vector<u8>", "vector<u8>"],
            return: [],
        },
        {
            name: "fee",
            visibility: "public",
            is_entry: false,
            is_view: true,
            generic_type_params: [],
            params: [],
            return: ["u32"],
        },
        {
            name: "accept_campaign_ownership",
            visibility: "public",
            is_entry: true,
            is_view: false,
            generic_type_params: [],
            params: ["&signer", "vector<u8>"],
            return: [],
        },
        {
            name: "accept_ownership",
            visibility: "public",
            is_entry: true,
            is_view: false,
            generic_type_params: [],
            params: ["&signer"],
            return: [],
        },
        {
            name: "updater",
            visibility: "public",
            is_entry: false,
            is_view: true,
            generic_type_params: [],
            params: [],
            return: ["address"],
        },
        {
            name: "campaign_reward",
            visibility: "public",
            is_entry: false,
            is_view: true,
            generic_type_params: [],
            params: ["vector<u8>", "address"],
            return: ["u64"],
        },
        {
            name: "claim_fees",
            visibility: "public",
            is_entry: true,
            is_view: false,
            generic_type_params: [],
            params: ["&signer", "address", "address"],
            return: [],
        },
        {
            name: "claim_rewards",
            visibility: "public",
            is_entry: true,
            is_view: false,
            generic_type_params: [],
            params: [
                "&signer",
                "vector<u8>",
                "vector<vector<u8>>",
                "address",
                "u64",
                "address",
            ],
            return: [],
        },
        {
            name: "claimable_fees",
            visibility: "public",
            is_entry: false,
            is_view: true,
            generic_type_params: [],
            params: ["address"],
            return: ["u64"],
        },
        {
            name: "claimed_campaign_reward",
            visibility: "public",
            is_entry: false,
            is_view: true,
            generic_type_params: [],
            params: ["vector<u8>", "address", "address"],
            return: ["u64"],
        },
        {
            name: "create_points_campaign",
            visibility: "public",
            is_entry: true,
            is_view: false,
            generic_type_params: [],
            params: [
                "&signer",
                "u64",
                "u64",
                "u32",
                "vector<u8>",
                "vector<u8>",
                "u64",
                "address",
            ],
            return: [],
        },
        {
            name: "create_reward_campaign",
            visibility: "public",
            is_entry: true,
            is_view: false,
            generic_type_params: [],
            params: [
                "&signer",
                "u64",
                "u64",
                "u32",
                "vector<u8>",
                "vector<u8>",
                "vector<address>",
                "vector<u64>",
            ],
            return: [],
        },
        {
            name: "fee_rebate",
            visibility: "public",
            is_entry: false,
            is_view: true,
            generic_type_params: [],
            params: ["address"],
            return: ["u32"],
        },
        {
            name: "init_module",
            visibility: "private",
            is_entry: true,
            is_view: false,
            generic_type_params: [],
            params: ["&signer"],
            return: [],
        },
        {
            name: "init_state",
            visibility: "public",
            is_entry: true,
            is_view: false,
            generic_type_params: [],
            params: ["&signer", "address", "address", "u32", "u64", "u64"],
            return: [],
        },
        {
            name: "minimum_campaign_duration",
            visibility: "public",
            is_entry: false,
            is_view: true,
            generic_type_params: [],
            params: [],
            return: ["u64"],
        },
        {
            name: "maximum_campaign_duration",
            visibility: "public",
            is_entry: false,
            is_view: true,
            generic_type_params: [],
            params: [],
            return: ["u64"],
        },
        {
            name: "minimum_fee_token_rate",
            visibility: "public",
            is_entry: false,
            is_view: true,
            generic_type_params: [],
            params: ["address"],
            return: ["u64"],
        },
        {
            name: "minimum_reward_token_rate",
            visibility: "public",
            is_entry: false,
            is_view: true,
            generic_type_params: [],
            params: ["address"],
            return: ["u64"],
        },
        {
            name: "pending_owner",
            visibility: "public",
            is_entry: false,
            is_view: true,
            generic_type_params: [],
            params: [],
            return: ["0x1::option::Option<address>"],
        },
        {
            name: "points_campaign_by_id",
            visibility: "public",
            is_entry: false,
            is_view: true,
            generic_type_params: [],
            params: ["vector<u8>"],
            return: [
                "0xe1c55a37640ff4582a47bacd396e3409056f2e931b5dd8dc6ef6ef131cf5cc9e::metrom::PointsCampaign",
            ],
        },
        {
            name: "points_campaign_id",
            visibility: "public",
            is_entry: false,
            is_view: true,
            generic_type_params: [],
            params: [
                "u64",
                "u64",
                "u32",
                "vector<u8>",
                "vector<u8>",
                "u64",
                "address",
            ],
            return: ["vector<u8>"],
        },
        {
            name: "recover_rewards",
            visibility: "public",
            is_entry: true,
            is_view: false,
            generic_type_params: [],
            params: [
                "&signer",
                "vector<u8>",
                "vector<vector<u8>>",
                "address",
                "u64",
                "address",
            ],
            return: [],
        },
        {
            name: "rewards_campaign_by_id",
            visibility: "public",
            is_entry: false,
            is_view: true,
            generic_type_params: [],
            params: ["vector<u8>"],
            return: [
                "0xe1c55a37640ff4582a47bacd396e3409056f2e931b5dd8dc6ef6ef131cf5cc9e::metrom::ReadonlyRewardsCampaign",
            ],
        },
        {
            name: "rewards_campaign_id",
            visibility: "public",
            is_entry: false,
            is_view: true,
            generic_type_params: [],
            params: [
                "u64",
                "u64",
                "u32",
                "vector<u8>",
                "vector<u8>",
                "vector<address>",
                "vector<u64>",
            ],
            return: ["vector<u8>"],
        },
        {
            name: "set_fee",
            visibility: "public",
            is_entry: true,
            is_view: false,
            generic_type_params: [],
            params: ["&signer", "u32"],
            return: [],
        },
        {
            name: "set_fee_rebate",
            visibility: "public",
            is_entry: true,
            is_view: false,
            generic_type_params: [],
            params: ["&signer", "address", "u32"],
            return: [],
        },
        {
            name: "set_maximum_campaign_duration",
            visibility: "public",
            is_entry: true,
            is_view: false,
            generic_type_params: [],
            params: ["&signer", "u64"],
            return: [],
        },
        {
            name: "set_minimum_campaign_duration",
            visibility: "public",
            is_entry: true,
            is_view: false,
            generic_type_params: [],
            params: ["&signer", "u64"],
            return: [],
        },
        {
            name: "set_minimum_fee_token_rate",
            visibility: "public",
            is_entry: true,
            is_view: false,
            generic_type_params: [],
            params: ["&signer", "address", "u64"],
            return: [],
        },
        {
            name: "set_minimum_reward_token_rate",
            visibility: "public",
            is_entry: true,
            is_view: false,
            generic_type_params: [],
            params: ["&signer", "address", "u64"],
            return: [],
        },
        {
            name: "set_updater",
            visibility: "public",
            is_entry: true,
            is_view: false,
            generic_type_params: [],
            params: ["&signer", "address"],
            return: [],
        },
        {
            name: "transfer_campaign_ownership",
            visibility: "public",
            is_entry: true,
            is_view: false,
            generic_type_params: [],
            params: ["&signer", "vector<u8>", "address"],
            return: [],
        },
        {
            name: "transfer_ownership",
            visibility: "public",
            is_entry: true,
            is_view: false,
            generic_type_params: [],
            params: ["&signer", "address"],
            return: [],
        },
    ],
    structs: [
        {
            name: "State",
            is_native: false,
            is_event: false,
            abilities: ["key"],
            generic_type_params: [],
            fields: [
                {
                    name: "treasury",
                    type: "0x1::account::SignerCapability",
                },
                {
                    name: "owner",
                    type: "address",
                },
                {
                    name: "pending_owner",
                    type: "0x1::option::Option<address>",
                },
                {
                    name: "updater",
                    type: "address",
                },
                {
                    name: "fee",
                    type: "u32",
                },
                {
                    name: "minimum_campaign_duration",
                    type: "u64",
                },
                {
                    name: "maximum_campaign_duration",
                    type: "u64",
                },
                {
                    name: "fee_rebate",
                    type: "0x1::smart_table::SmartTable<address, u32>",
                },
                {
                    name: "claimable_fees",
                    type: "0x1::smart_table::SmartTable<address, u64>",
                },
                {
                    name: "minimum_reward_token_rate",
                    type: "0x1::smart_table::SmartTable<address, u64>",
                },
                {
                    name: "minimum_fee_token_rate",
                    type: "0x1::smart_table::SmartTable<address, u64>",
                },
                {
                    name: "points_campaign",
                    type: "0x1::smart_table::SmartTable<vector<u8>, 0xe1c55a37640ff4582a47bacd396e3409056f2e931b5dd8dc6ef6ef131cf5cc9e::metrom::PointsCampaign>",
                },
                {
                    name: "rewards_campaign",
                    type: "0x1::smart_table::SmartTable<vector<u8>, 0xe1c55a37640ff4582a47bacd396e3409056f2e931b5dd8dc6ef6ef131cf5cc9e::metrom::RewardsCampaign>",
                },
            ],
        },
        {
            name: "Initialize",
            is_native: false,
            is_event: true,
            abilities: ["drop", "store"],
            generic_type_params: [],
            fields: [
                {
                    name: "owner",
                    type: "address",
                },
                {
                    name: "updater",
                    type: "address",
                },
                {
                    name: "fee",
                    type: "u32",
                },
                {
                    name: "minimum_campaign_duration",
                    type: "u64",
                },
                {
                    name: "maximum_campaign_duration",
                    type: "u64",
                },
            ],
        },
        {
            name: "AcceptCampaignOwnership",
            is_native: false,
            is_event: true,
            abilities: ["drop", "store"],
            generic_type_params: [],
            fields: [
                {
                    name: "campaign_id",
                    type: "vector<u8>",
                },
                {
                    name: "owner",
                    type: "address",
                },
            ],
        },
        {
            name: "AcceptOwnership",
            is_native: false,
            is_event: true,
            abilities: ["drop", "store"],
            generic_type_params: [],
            fields: [
                {
                    name: "owner",
                    type: "address",
                },
            ],
        },
        {
            name: "ClaimFee",
            is_native: false,
            is_event: true,
            abilities: ["drop", "store"],
            generic_type_params: [],
            fields: [
                {
                    name: "token",
                    type: "address",
                },
                {
                    name: "amount",
                    type: "u64",
                },
                {
                    name: "receiver",
                    type: "address",
                },
            ],
        },
        {
            name: "ClaimReward",
            is_native: false,
            is_event: true,
            abilities: ["drop", "store"],
            generic_type_params: [],
            fields: [
                {
                    name: "campaign_id",
                    type: "vector<u8>",
                },
                {
                    name: "token",
                    type: "address",
                },
                {
                    name: "amount",
                    type: "u64",
                },
                {
                    name: "receiver",
                    type: "address",
                },
            ],
        },
        {
            name: "CreatePointsCampaign",
            is_native: false,
            is_event: true,
            abilities: ["drop", "store"],
            generic_type_params: [],
            fields: [
                {
                    name: "id",
                    type: "vector<u8>",
                },
                {
                    name: "owner",
                    type: "address",
                },
                {
                    name: "from",
                    type: "u64",
                },
                {
                    name: "to",
                    type: "u64",
                },
                {
                    name: "kind",
                    type: "u32",
                },
                {
                    name: "data",
                    type: "vector<u8>",
                },
                {
                    name: "specification_hash",
                    type: "vector<u8>",
                },
                {
                    name: "points",
                    type: "u64",
                },
                {
                    name: "fee_token",
                    type: "address",
                },
                {
                    name: "fee",
                    type: "u64",
                },
            ],
        },
        {
            name: "CreateRewardsCampaign",
            is_native: false,
            is_event: true,
            abilities: ["drop", "store"],
            generic_type_params: [],
            fields: [
                {
                    name: "id",
                    type: "vector<u8>",
                },
                {
                    name: "owner",
                    type: "address",
                },
                {
                    name: "from",
                    type: "u64",
                },
                {
                    name: "to",
                    type: "u64",
                },
                {
                    name: "kind",
                    type: "u32",
                },
                {
                    name: "data",
                    type: "vector<u8>",
                },
                {
                    name: "specification_hash",
                    type: "vector<u8>",
                },
                {
                    name: "reward_tokens",
                    type: "vector<address>",
                },
                {
                    name: "reward_amounts",
                    type: "vector<u64>",
                },
                {
                    name: "reward_fees",
                    type: "vector<u64>",
                },
            ],
        },
        {
            name: "DistributeReward",
            is_native: false,
            is_event: true,
            abilities: ["drop", "store"],
            generic_type_params: [],
            fields: [
                {
                    name: "campaign_id",
                    type: "vector<u8>",
                },
                {
                    name: "root",
                    type: "vector<u8>",
                },
            ],
        },
        {
            name: "PointsCampaign",
            is_native: false,
            is_event: false,
            abilities: ["copy", "store", "key"],
            generic_type_params: [],
            fields: [
                {
                    name: "owner",
                    type: "address",
                },
                {
                    name: "pending_owner",
                    type: "0x1::option::Option<address>",
                },
                {
                    name: "from",
                    type: "u64",
                },
                {
                    name: "to",
                    type: "u64",
                },
                {
                    name: "kind",
                    type: "u32",
                },
                {
                    name: "data",
                    type: "vector<u8>",
                },
                {
                    name: "specification_hash",
                    type: "vector<u8>",
                },
                {
                    name: "points",
                    type: "u64",
                },
            ],
        },
        {
            name: "ReadonlyRewardsCampaign",
            is_native: false,
            is_event: false,
            abilities: [],
            generic_type_params: [],
            fields: [
                {
                    name: "owner",
                    type: "address",
                },
                {
                    name: "pending_owner",
                    type: "0x1::option::Option<address>",
                },
                {
                    name: "from",
                    type: "u64",
                },
                {
                    name: "to",
                    type: "u64",
                },
                {
                    name: "kind",
                    type: "u32",
                },
                {
                    name: "data",
                    type: "vector<u8>",
                },
                {
                    name: "specification_hash",
                    type: "vector<u8>",
                },
                {
                    name: "root",
                    type: "vector<u8>",
                },
            ],
        },
        {
            name: "RecoverReward",
            is_native: false,
            is_event: true,
            abilities: ["drop", "store"],
            generic_type_params: [],
            fields: [
                {
                    name: "campaign_id",
                    type: "vector<u8>",
                },
                {
                    name: "token",
                    type: "address",
                },
                {
                    name: "amount",
                    type: "u64",
                },
                {
                    name: "receiver",
                    type: "address",
                },
            ],
        },
        {
            name: "Reward",
            is_native: false,
            is_event: false,
            abilities: ["store", "key"],
            generic_type_params: [],
            fields: [
                {
                    name: "amount",
                    type: "u64",
                },
                {
                    name: "claimed",
                    type: "0x1::smart_table::SmartTable<address, u64>",
                },
            ],
        },
        {
            name: "RewardsCampaign",
            is_native: false,
            is_event: false,
            abilities: ["store", "key"],
            generic_type_params: [],
            fields: [
                {
                    name: "owner",
                    type: "address",
                },
                {
                    name: "pending_owner",
                    type: "0x1::option::Option<address>",
                },
                {
                    name: "from",
                    type: "u64",
                },
                {
                    name: "to",
                    type: "u64",
                },
                {
                    name: "kind",
                    type: "u32",
                },
                {
                    name: "data",
                    type: "vector<u8>",
                },
                {
                    name: "specification_hash",
                    type: "vector<u8>",
                },
                {
                    name: "root",
                    type: "vector<u8>",
                },
                {
                    name: "reward",
                    type: "0x1::smart_table::SmartTable<address, 0xe1c55a37640ff4582a47bacd396e3409056f2e931b5dd8dc6ef6ef131cf5cc9e::metrom::Reward>",
                },
            ],
        },
        {
            name: "SetFee",
            is_native: false,
            is_event: true,
            abilities: ["drop", "store"],
            generic_type_params: [],
            fields: [
                {
                    name: "fee",
                    type: "u32",
                },
            ],
        },
        {
            name: "SetFeeRebate",
            is_native: false,
            is_event: true,
            abilities: ["drop", "store"],
            generic_type_params: [],
            fields: [
                {
                    name: "account",
                    type: "address",
                },
                {
                    name: "rebate",
                    type: "u32",
                },
            ],
        },
        {
            name: "SetMaximumCampaignDuration",
            is_native: false,
            is_event: true,
            abilities: ["drop", "store"],
            generic_type_params: [],
            fields: [
                {
                    name: "maximum_campaign_duration",
                    type: "u64",
                },
            ],
        },
        {
            name: "SetMinimumCampaignDuration",
            is_native: false,
            is_event: true,
            abilities: ["drop", "store"],
            generic_type_params: [],
            fields: [
                {
                    name: "minimum_campaign_duration",
                    type: "u64",
                },
            ],
        },
        {
            name: "SetMinimumFeeTokenRate",
            is_native: false,
            is_event: true,
            abilities: ["drop", "store"],
            generic_type_params: [],
            fields: [
                {
                    name: "token",
                    type: "address",
                },
                {
                    name: "minimum_rate",
                    type: "u64",
                },
            ],
        },
        {
            name: "SetMinimumRewardTokenRate",
            is_native: false,
            is_event: true,
            abilities: ["drop", "store"],
            generic_type_params: [],
            fields: [
                {
                    name: "token",
                    type: "address",
                },
                {
                    name: "minimum_rate",
                    type: "u64",
                },
            ],
        },
        {
            name: "SetUpdater",
            is_native: false,
            is_event: true,
            abilities: ["drop", "store"],
            generic_type_params: [],
            fields: [
                {
                    name: "updater",
                    type: "address",
                },
            ],
        },
        {
            name: "TransferCampaignOwnership",
            is_native: false,
            is_event: true,
            abilities: ["drop", "store"],
            generic_type_params: [],
            fields: [
                {
                    name: "campaign_id",
                    type: "vector<u8>",
                },
                {
                    name: "owner",
                    type: "address",
                },
            ],
        },
        {
            name: "TransferOwnership",
            is_native: false,
            is_event: true,
            abilities: ["drop", "store"],
            generic_type_params: [],
            fields: [
                {
                    name: "owner",
                    type: "address",
                },
            ],
        },
    ],
} as const;
